apiVersion: v2
name: scheduling-report-api
description: Scheduling Report Configuration API - Go Fiber REST API

type: application

# This is the chart version
version: 0.1.0

# This is the version number of the application being deployed
# This will be replaced by CI/CD pipeline with actual version
AppVersion: J_APP_VERSION
